const cars = [
  {
    make: "Ford",
    model: [
      "EcoSport",
      "Endura",
      "Escape",
      "Everest",
      "F-150",
      "Fiesta",
      "Focus",
      "Mondeo",
      "Mustang",
      "Puma",
      "Ranger",
      "Transit",
      "Transit Custom",
    ],
  },
  {
    make: "Honda",
    model: [
      "Accord",
      "City",
      "Civic",
      "CR-V",
      "HR-V",
      "Jazz",
      "NSX",
      "Odyssey",
    ],
  },
  {
    make: "Hyudai",
    model: [
      "Elantra",
      "i20",
      "i30",
      "iLoad",
      "iMax",
      "Ioniq",
      "Ioniq 5",
      "Kona",
      "Palisade",
      "Santa Fe",
      "Sonata",
      "Staria",
      "Tucson",
      "Veloster",
      "Venue",
    ],
  },
  {
    make: "Kia",
    model: [
      "Carnival",
      "Cerato",
      "EV6",
      "Niro",
      "Optima",
      "Picanto",
      "Rio",
      "Rondo",
      "Seltos",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
      "Stonic",
    ],
  },
  {
    make: "Jaguar",
    model: ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF", "XJ"],
  },
  {
    make: "Lamborghini",
    model: ["Aventador", "Huracan", "Urus"],
  },
  {
    make: "Land Rover",
    model: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
    ],
  },
  {
    make: "Mazda",
    model: [
      "BT-50",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-60",
      "CX-8",
      "CX-9",
      "Mazda 2",
      "Mazda 3",
      "Mazda 6",
      "MX-30",
      "MX-5",
    ],
  },
  {
    make: "McLaren",
    model: ["540C", "570GT", "570S", "600LT", "650S", "720S", "GT"],
  },
  {
    make: "Tesla",
    model: ["Model 3", "Model S", "Model X", "Model Y"],
  },
  {
    make: "Toyota",
    model: [
      "86",
      "bZ4X",
      "C-HR",
      "Camry",
      "Corolla",
      "Fortuner",
      "Granvia",
      "HiAce",
      "HiLux",
      "Kluger",
      "LandCruiser",
      "LandCruiser 70",
      "LandCruiser Prado",
      "Mirai",
      "Prius",
      "Prius V",
      "RAV 4",
      "Supra",
      "Yaris",
      "Yaris Cross",
    ],
  },
];

export default cars;
